version: '3.8'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.8
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports: [ "9200:9200", "9300:9300" ]
  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.8
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports: [ "5601:5601" ]
    depends_on: [ es ]
